export enum Bird {
  AfricanGreyParrot = "african_grey_parrot",
  Budgerigar = "budgerigar",
  Canary = "canary",
  Cockatiel = "cockatiel",
  Cockatoo = "cockatoo",
  Conure = "conure",
  Dove = "dove",
  EclectusParrot = "eclectus_parrot",
  Finch = "finch",
  Lovebird = "lovebird",
  Macaw = "macaw",
  Mynah = "mynah",
  Parakeet = "parakeet",
  Parrotlet = "parrotlet",
  Pigeon = "pigeon",
  QuakerParrot = "quaker_parrot",
  RainbowLorikeet = "rainbow_lorikeet",
  Rosella = "rosella",
  SenegalParrot = "senegal_parrot",
  Starling = "starling",
}
