export enum Reptile {
  BallPython = "ball_python",
  BeardedDragon = "bearded_dragon",
  BlueTongueSkink = "blue_tongue_skink",
  BoxTurtle = "box_turtle",
  Chameleon = "chameleon",
  CornSnake = "corn_snake",
  CrestedGecko = "crested_gecko",
  GargoyleGecko = "gargoyle_gecko",
  GreenAnole = "green_anole",
  GreenIguana = "green_iguana",
  HermannsTortoise = "hermanns_tortoise",
  JacksonsChameleon = "jacksons_chameleon",
  KingSnake = "king_snake",
  LeopardGecko = "leopard_gecko",
  MaliUromastyx = "mali_uromastyx",
  MapTurtle = "map_turtle",
  PaintedTurtle = "painted_turtle",
  PantherChameleon = "panther_chameleon",
  RedEaredSlider = "red_eared_slider",
  RussianTortoise = "russian_tortoise",
  SavannahMonitor = "savannah_monitor",
  SulcataTortoise = "sulcata_tortoise",
  Tegu = "tegu",
  TokayGecko = "tokay_gecko",
  Uromastyx = "uromastyx",
  WaterDragon = "water_dragon",
}
